### PR TITLE
Fix duplicate answers on question edit

### PR DESCRIPTION
**Pull request by fvosburgh**
## Changes 

I added some code to manually update each answer when editing a question. I pass the ID as a hidden field and use that as an index for ActiveRecord to get the correct answer record. I then update each attribute.

## Context 

Editing a questions answers duplicated each answer. This fixes that

## Testing 

Create a new question with new answers. Then, go back and edit the answers and save. There should be no copies of the old answers or any duplicates.

## Pre-merge checklist 

- [x] Build succeeds locally and in CI
- [x] Proper documentation
- [x] Tests
- [x] Git history clean

### CODE REVIEW

**Review by Bikranta — COMMENTED** [review]
i don't think this is working. while editing, if there are two same answer, this code does nothing.

**Review by Bikranta — COMMENTED** [review]
Sorry, i was looking different thing. everything works.

**Review by Bikranta — APPROVED** [review]

**Comment by strburst** [comment]
@fvosburgh while you're at it, it would probably be good to remember to fixup that cleanup commit. :+1:

**Comment by strburst** [comment]
@rmkeezer noooooo plz you should have done the squash merge nooooo

(It's ok :stuck_out_tongue:.)

**Pull request merged**
